# STASIUN
NAMA_STASIUN_ASAL = "BANYUWANGI KOTA"
NAMA_STASIUN_TUJUAN = "PURWOSARI"

# TANGGAL
TANGGAL_KEBERANGKATAN = "12"
BULAN_KEBERANGKATAN = "Apr"
PENUMPANG_DEWASA = "4"

# KERETA
NAMA_KERETA = "SRI TANJUNG"
GERBONG_KERETA = "EKO-4"

# LOGIN
USERNAME = ""
PASSWORD = ""

# LOGIN BYPASS
ALAMAT_PEMESAN = ""
NOMOR_PEMESAN = ""
EMAIL_PEMESAN = "@gmail.com"

# PEMBAYARAN
NAMA_BANK = "BANK BRI"

# DATA PENUMPANG
# [4:00 AM, 2/25/2024] Syafiq: 
NAMA_PENUMPANG_1 = ""
NIK_PENUMPANG_1 = ""
# KURSI_PENUMPANG_1 = ""

# [4:00 AM, 2/25/2024] Syafiq: 
NAMA_PENUMPANG_2 = ""
NIK_PENUMPANG_2 = ""
# KURSI_PENUMPANG_2 = ""

# [4:00 AM, 2/25/2024] Syafiq: 
NAMA_PENUMPANG_3 = ""
NIK_PENUMPANG_3 = ""
# KURSI_PENUMPANG_3 = ""

# [4:00 AM, 2/25/2024] Syafiq: 
NAMA_PENUMPANG_4 = ""
NIK_PENUMPANG_4 = ""
# KURSI_PENUMPANG_4 = ""